- imageUrl: https://github.com/$owner/$repo/actions/workflows/codeql.yml/badge.svg?branch=$branchName
  url: https://github.com/$owner/$repo/actions/workflows/codeql.yml?query=branch:$branchName

- label: "Warn"
  message: "Unchecked Tasks"
  color: "yellow"
  when: "$payload.pull_request.body && $payload.pull_request.body.includes('- [ ]')"

- label: "Completed" 
  message: "Tasks"
  color: "green"
  when: "$payload.pull_request.body && (!$payload.pull_request.body.includes('- [ ]') && $payload.pull_request.body.includes('- [x]'))"

- message: "Work in Progress"
  color: "yellow"
  when: "$payload.pull_request.body && ($payload.pull_request.body.includes('- [ ]') && $payload.pull_request.labels.some(label => label.name === 'in progress'))"

- message: "Done"
  color: "green"
  when: "$payload.pull_request.labels.some(label => label.name === 'done')"

- message: "Won't fix"
  color: "red"
  when: "$payload.pull_request.labels.some(label => label.name === 'wontfix')"

- message: "Duplicate"
  color: "grey"
  when: "$payload.pull_request.labels.some(label => label.name === 'duplicate')"