name: Label Automation

on:
  pull_request_target:
    types:
      - closed
  pull_request:
    types:
      - closed
  issues:
    types:
      - closed

jobs:
  scrap:
    name: Mark as Scrapped
    if: github.event.issue.state_reason == 'not planned' || github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v4.0.0
        with:
          config-path: .github/labeler_wontfix.yml
          config-repo: Julexar/Item-Store
          github-token: ${{ secrets.WORKFLOW_TOKEN }}

  done:
    name: Mark as Done
    if: github.event.issue.state_reason == 'completed' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v4.0.0
        with:
          config-path: .github/labeler_done.yml
          config-repo: Julexar/Item-Store
          github-token: ${{ secrets.WORKFLOW_TOKEN }}

  remove:
    name: Remove outdated Labels
    runs-on: ubuntu-latest
    if: (github.event.issue.state_reason == 'completed' && contains(github.event.issue.labels.*.name, 'in progress')) || (github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'in progress'))
    steps:
      - run: sleep 1
      - uses: mondeja/remove-labels-gh-action@v1.1.1
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          labels: in progress