name: Label Automation

on:
  pull_request: 
    types:
      - synchronize

jobs:
  label:
    name: Mark as In Progress 
    if: github.event.pull_request.merged == false && !contains(github.events.pull_request.labels.*.name, 'in progress') && github.event.pull_request.assignee != null
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v4.0.0
        with:
          config-path: .github/labeler_wip.yml
          config-repo: Julexar/Item-Store
          github-token: ${{ secrets.WORKFLOW_TOKEN }}